//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlexPacientes.Labels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlexPacientes.Labels.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Me.
        /// </summary>
        internal static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Mind Help.
        /// </summary>
        internal static string AboutMH {
            get {
                return ResourceManager.GetString("AboutMH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        internal static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account has been deleted.
        /// </summary>
        internal static string AccountDeleted {
            get {
                return ResourceManager.GetString("AccountDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        internal static string AccountQuestionNegative {
            get {
                return ResourceManager.GetString("AccountQuestionNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you already have an account?.
        /// </summary>
        internal static string AccountQuestionPositive {
            get {
                return ResourceManager.GetString("AccountQuestionPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a title.
        /// </summary>
        internal static string AddATitle {
            get {
                return ResourceManager.GetString("AddATitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Note.
        /// </summary>
        internal static string AddNewNote {
            get {
                return ResourceManager.GetString("AddNewNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields required.
        /// </summary>
        internal static string AllFieldsRequired {
            get {
                return ResourceManager.GetString("AllFieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply coupon.
        /// </summary>
        internal static string ApplyCoupon {
            get {
                return ResourceManager.GetString("ApplyCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Appoiments Available.
        /// </summary>
        internal static string AppoimentsAvailableFormat {
            get {
                return ResourceManager.GetString("AppoimentsAvailableFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Canceled.
        /// </summary>
        internal static string AppointmentCanceled {
            get {
                return ResourceManager.GetString("AppointmentCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your appointment details.
        /// </summary>
        internal static string AppointmentDetails {
            get {
                return ResourceManager.GetString("AppointmentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppointmentFinished.
        /// </summary>
        internal static string AppointmentFinished {
            get {
                return ResourceManager.GetString("AppointmentFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment in Progress.
        /// </summary>
        internal static string AppointmentInProgress {
            get {
                return ResourceManager.GetString("AppointmentInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Rejected.
        /// </summary>
        internal static string AppointmentRejected {
            get {
                return ResourceManager.GetString("AppointmentRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Scheduled.
        /// </summary>
        internal static string AppointmentScheduled {
            get {
                return ResourceManager.GetString("AppointmentScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Updated.
        /// </summary>
        internal static string AppointmentUpdated {
            get {
                return ResourceManager.GetString("AppointmentUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment update error, Try again later.
        /// </summary>
        internal static string AppointmentUpdatedError {
            get {
                return ResourceManager.GetString("AppointmentUpdatedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Hours.
        /// </summary>
        internal static string AvailableHours {
            get {
                return ResourceManager.GetString("AvailableHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our {0} available therapists.
        /// </summary>
        internal static string AvailableTherapistsFormat {
            get {
                return ResourceManager.GetString("AvailableTherapistsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heal with the help of our expert therapists.
        /// </summary>
        internal static string BeBetterWithOurSpecialist {
            get {
                return ResourceManager.GetString("BeBetterWithOurSpecialist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate.
        /// </summary>
        internal static string Birthdate {
            get {
                return ResourceManager.GetString("Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Again.
        /// </summary>
        internal static string BookAgain {
            get {
                return ResourceManager.GetString("BookAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book an Appointment.
        /// </summary>
        internal static string BookAnAppointment {
            get {
                return ResourceManager.GetString("BookAnAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking.
        /// </summary>
        internal static string Booking {
            get {
                return ResourceManager.GetString("Booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookings.
        /// </summary>
        internal static string Bookings {
            get {
                return ResourceManager.GetString("Bookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to book this session again?.
        /// </summary>
        internal static string BookSession_01 {
            get {
                return ResourceManager.GetString("BookSession_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        internal static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La suscripción actual sea cancelada, podrás continuar usar el servicio hasta que te termine tu paquete contratado..
        /// </summary>
        internal static string CancelExtraDescription {
            get {
                return ResourceManager.GetString("CancelExtraDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation Options.
        /// </summary>
        internal static string CancellationOptions {
            get {
                return ResourceManager.GetString("CancellationOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        internal static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chats.
        /// </summary>
        internal static string Chats {
            get {
                return ResourceManager.GetString("Chats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        internal static string ConfirmPasswordPlaceholder {
            get {
                return ResourceManager.GetString("ConfirmPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!.
        /// </summary>
        internal static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultation date and time.
        /// </summary>
        internal static string ConsultationDateTime {
            get {
                return ResourceManager.GetString("ConsultationDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Consultation includes.
        /// </summary>
        internal static string ConsultationIncludes {
            get {
                return ResourceManager.GetString("ConsultationIncludes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultation Type.
        /// </summary>
        internal static string ConsultationType {
            get {
                return ResourceManager.GetString("ConsultationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string CreditCardBrand {
            get {
                return ResourceManager.GetString("CreditCardBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to use this card as the default?.
        /// </summary>
        internal static string CreditCardDefaultQuestion {
            get {
                return ResourceManager.GetString("CreditCardDefaultQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        internal static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV.
        /// </summary>
        internal static string CVV {
            get {
                return ResourceManager.GetString("CVV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date &amp; Hour.
        /// </summary>
        internal static string DateAndHour {
            get {
                return ResourceManager.GetString("DateAndHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}d.
        /// </summary>
        internal static string DaysAgoFormat {
            get {
                return ResourceManager.GetString("DaysAgoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is your chat!.
        /// </summary>
        internal static string DefaultChatMessage {
            get {
                return ResourceManager.GetString("DefaultChatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        internal static string DeleteAccountLabel {
            get {
                return ResourceManager.GetString("DeleteAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you delete your account, all your related information will be deleted.
        /// </summary>
        internal static string DeleteAccountMessage {
            get {
                return ResourceManager.GetString("DeleteAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disponibility.
        /// </summary>
        internal static string Disponibility {
            get {
                return ResourceManager.GetString("Disponibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        internal static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string EndHour {
            get {
                return ResourceManager.GetString("EndHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter coupon.
        /// </summary>
        internal static string EnterCoupon {
            get {
                return ResourceManager.GetString("EnterCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting payment method.
        /// </summary>
        internal static string ErrorDeletingPaymentMethod {
            get {
                return ResourceManager.GetString("ErrorDeletingPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to enter your password.
        /// </summary>
        internal static string ErrorEnterPassword {
            get {
                return ResourceManager.GetString("ErrorEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password confirmation does not match.
        /// </summary>
        internal static string ErrorMustBeSamePassword {
            get {
                return ResourceManager.GetString("ErrorMustBeSamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least 5 characteres and max 16.
        /// </summary>
        internal static string ErrorPasswordLenght {
            get {
                return ResourceManager.GetString("ErrorPasswordLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        internal static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        internal static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequently asked questions.
        /// </summary>
        internal static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedbacks.
        /// </summary>
        internal static string Feedbacks {
            get {
                return ResourceManager.GetString("Feedbacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Feedbacks.
        /// </summary>
        internal static string FeedbacksFormat {
            get {
                return ResourceManager.GetString("FeedbacksFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email has been sent to reset the password to the address: {0}.
        /// </summary>
        internal static string ForgotPasswordEmailFormat {
            get {
                return ResourceManager.GetString("ForgotPasswordEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email adress and we’ll send you a link so you can reset your password.
        /// </summary>
        internal static string ForgotPasswordMessage {
            get {
                return ResourceManager.GetString("ForgotPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string ForgotPasswordQuestion {
            get {
                return ResourceManager.GetString("ForgotPasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free cancellation 24 hours.
        /// </summary>
        internal static string FreeCancellation {
            get {
                return ResourceManager.GetString("FreeCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        internal static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something goes wrong..
        /// </summary>
        internal static string GenericErrorMessage {
            get {
                return ResourceManager.GetString("GenericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry.
        /// </summary>
        internal static string GenericErrorTittle {
            get {
                return ResourceManager.GetString("GenericErrorTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este chat te servira para cualquier pregunta que tengas.
        /// </summary>
        internal static string HereYouCanChat {
            get {
                return ResourceManager.GetString("HereYouCanChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What challenges do you face today?.
        /// </summary>
        internal static string HomeChallengesTitle {
            get {
                return ResourceManager.GetString("HomeChallengesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One hour video session.
        /// </summary>
        internal static string HourVideoSession {
            get {
                return ResourceManager.GetString("HourVideoSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid promo code.
        /// </summary>
        internal static string InvalidCoupon {
            get {
                return ResourceManager.GetString("InvalidCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay Logged In.
        /// </summary>
        internal static string KeepLoggedIn {
            get {
                return ResourceManager.GetString("KeepLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        internal static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library not available.
        /// </summary>
        internal static string LibraryNotAvailable {
            get {
                return ResourceManager.GetString("LibraryNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login now.
        /// </summary>
        internal static string LoginNow {
            get {
                return ResourceManager.GetString("LoginNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to Mind help.
        /// </summary>
        internal static string LoginToMindhelp {
            get {
                return ResourceManager.GetString("LoginToMindhelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Appointment.
        /// </summary>
        internal static string MakeAppointment {
            get {
                return ResourceManager.GetString("MakeAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${0:N0}.
        /// </summary>
        internal static string MoneyFormat {
            get {
                return ResourceManager.GetString("MoneyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${0:N2}.
        /// </summary>
        internal static string MoneyWithCentsFormat {
            get {
                return ResourceManager.GetString("MoneyWithCentsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}m.
        /// </summary>
        internal static string MonthAgoFormat {
            get {
                return ResourceManager.GetString("MonthAgoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOST POPULAR.
        /// </summary>
        internal static string MostPopular {
            get {
                return ResourceManager.GetString("MostPopular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Appointment.
        /// </summary>
        internal static string NewAppointment {
            get {
                return ResourceManager.GetString("NewAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New message recceived.
        /// </summary>
        internal static string NewMessageReceived {
            get {
                return ResourceManager.GetString("NewMessageReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new password.
        /// </summary>
        internal static string NewPasswordPlaceholder {
            get {
                return ResourceManager.GetString("NewPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have good news for you!.
        /// </summary>
        internal static string NewPushArrive {
            get {
                return ResourceManager.GetString("NewPushArrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New session requested by {0}.
        /// </summary>
        internal static string NewServiceRequested {
            get {
                return ResourceManager.GetString("NewServiceRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} non-refundable cancellation.
        /// </summary>
        internal static string NonRefundableCancellation {
            get {
                return ResourceManager.GetString("NonRefundableCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have a registered payment method.
        /// </summary>
        internal static string NoPaymentMethodsAvailable {
            get {
                return ResourceManager.GetString("NoPaymentMethodsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have a payment method to make an appointment.
        /// </summary>
        internal static string NoPaymentMethodsAvailableDescription {
            get {
                return ResourceManager.GetString("NoPaymentMethodsAvailableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no slots available.
        /// </summary>
        internal static string NoSlotsAvailable {
            get {
                return ResourceManager.GetString("NoSlotsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Subscription.
        /// </summary>
        internal static string NoSubscription {
            get {
                return ResourceManager.GetString("NoSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule meetings one by one.
        /// </summary>
        internal static string NoSubscriptionDescription {
            get {
                return ResourceManager.GetString("NoSubscriptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable hours.
        /// </summary>
        internal static string NotAvailableHours {
            get {
                return ResourceManager.GetString("NotAvailableHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera not available.
        /// </summary>
        internal static string NotCameraAvailable {
            get {
                return ResourceManager.GetString("NotCameraAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to now.
        /// </summary>
        internal static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        internal static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter old password.
        /// </summary>
        internal static string OldPasswordPlaceholder {
            get {
                return ResourceManager.GetString("OldPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops.
        /// </summary>
        internal static string Oops {
            get {
                return ResourceManager.GetString("Oops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Connected.
        /// </summary>
        internal static string PartnerConnected {
            get {
                return ResourceManager.GetString("PartnerConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past.
        /// </summary>
        internal static string Past {
            get {
                return ResourceManager.GetString("Past", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment card Added!.
        /// </summary>
        internal static string PaymentCardCreated {
            get {
                return ResourceManager.GetString("PaymentCardCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding payment method .
        /// </summary>
        internal static string PaymentMethodAddedError {
            get {
                return ResourceManager.GetString("PaymentMethodAddedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method added.
        /// </summary>
        internal static string PaymentMethodAddedSucessfuly {
            get {
                return ResourceManager.GetString("PaymentMethodAddedSucessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Methods.
        /// </summary>
        internal static string PaymentMethods {
            get {
                return ResourceManager.GetString("PaymentMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Rejected.
        /// </summary>
        internal static string PaymentRejected {
            get {
                return ResourceManager.GetString("PaymentRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo &amp; Video Library.
        /// </summary>
        internal static string PhotoAndLibrary {
            get {
                return ResourceManager.GetString("PhotoAndLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place request.
        /// </summary>
        internal static string PlaceRequest {
            get {
                return ResourceManager.GetString("PlaceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans.
        /// </summary>
        internal static string Plans {
            get {
                return ResourceManager.GetString("Plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${0:F2}.
        /// </summary>
        internal static string PriceFormat {
            get {
                return ResourceManager.GetString("PriceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data has been updated.
        /// </summary>
        internal static string ProfileDataUpdated {
            get {
                return ResourceManager.GetString("ProfileDataUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo.
        /// </summary>
        internal static string Promotion {
            get {
                return ResourceManager.GetString("Promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question has been sent.
        /// </summary>
        internal static string QuestionSended {
            get {
                return ResourceManager.GetString("QuestionSended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratings &amp; Reviews.
        /// </summary>
        internal static string RatingsAndReviews {
            get {
                return ResourceManager.GetString("RatingsAndReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You.
        /// </summary>
        internal static string RatingSessionLabel_01 {
            get {
                return ResourceManager.GetString("RatingSessionLabel_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your one hour session has been completed.
        /// </summary>
        internal static string RatingSessionLabel_02 {
            get {
                return ResourceManager.GetString("RatingSessionLabel_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Review.
        /// </summary>
        internal static string RatingSessionLabel_03 {
            get {
                return ResourceManager.GetString("RatingSessionLabel_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell us Why.
        /// </summary>
        internal static string RatingSessionLabel_04 {
            get {
                return ResourceManager.GetString("RatingSessionLabel_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe your experience with the doctor.
        /// </summary>
        internal static string RatingSessionLabel_05 {
            get {
                return ResourceManager.GetString("RatingSessionLabel_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        internal static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested.
        /// </summary>
        internal static string Requested {
            get {
                return ResourceManager.GetString("Requested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reschedule.
        /// </summary>
        internal static string Reschedule {
            get {
                return ResourceManager.GetString("Reschedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a day to see the available slots.
        /// </summary>
        internal static string SelectADay {
            get {
                return ResourceManager.GetString("SelectADay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Date and Time.
        /// </summary>
        internal static string SelectDateTime {
            get {
                return ResourceManager.GetString("SelectDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one action.
        /// </summary>
        internal static string SelectOneAction {
            get {
                return ResourceManager.GetString("SelectOneAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send an Email.
        /// </summary>
        internal static string SendAnEmail {
            get {
                return ResourceManager.GetString("SendAnEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service is not available on this moment.
        /// </summary>
        internal static string ServiceNotAvailable {
            get {
                return ResourceManager.GetString("ServiceNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Finished.
        /// </summary>
        internal static string SessionFinished {
            get {
                return ResourceManager.GetString("SessionFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You successfully registered! Now log in with your account..
        /// </summary>
        internal static string SignUpSuccessful {
            get {
                return ResourceManager.GetString("SignUpSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string StartHour {
            get {
                return ResourceManager.GetString("StartHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start writing….
        /// </summary>
        internal static string StartWriting {
            get {
                return ResourceManager.GetString("StartWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Review.
        /// </summary>
        internal static string SubmitReview {
            get {
                return ResourceManager.GetString("SubmitReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to want to continue buying the {0} subscription?.
        /// </summary>
        internal static string SubscriptionBuyQuestion {
            get {
                return ResourceManager.GetString("SubscriptionBuyQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have purchased the subscription.
        /// </summary>
        internal static string SubscriptionSuccesfulPurchase {
            get {
                return ResourceManager.GetString("SubscriptionSuccesfulPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total consultation fee.
        /// </summary>
        internal static string TotalConsultationFee {
            get {
                return ResourceManager.GetString("TotalConsultationFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        internal static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your total savings.
        /// </summary>
        internal static string TotalSavings {
            get {
                return ResourceManager.GetString("TotalSavings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete account, try again in another moment.
        /// </summary>
        internal static string UnableToDeleteAccount {
            get {
                return ResourceManager.GetString("UnableToDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited text messages for week.
        /// </summary>
        internal static string UnlimitedTextMessages {
            get {
                return ResourceManager.GetString("UnlimitedTextMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming.
        /// </summary>
        internal static string Upcoming {
            get {
                return ResourceManager.GetString("Upcoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon applied successfully.
        /// </summary>
        internal static string ValidCoupon {
            get {
                return ResourceManager.GetString("ValidCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Call.
        /// </summary>
        internal static string VideoCall {
            get {
                return ResourceManager.GetString("VideoCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for the Dr. to join the video call.
        /// </summary>
        internal static string VideoSessionInstructions {
            get {
                return ResourceManager.GetString("VideoSessionInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All.
        /// </summary>
        internal static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Less.
        /// </summary>
        internal static string ViewLess {
            get {
                return ResourceManager.GetString("ViewLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View More.
        /// </summary>
        internal static string ViewMore {
            get {
                return ResourceManager.GetString("ViewMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Resume.
        /// </summary>
        internal static string ViewResume {
            get {
                return ResourceManager.GetString("ViewResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}w.
        /// </summary>
        internal static string WeeksAgoFormat {
            get {
                return ResourceManager.GetString("WeeksAgoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back to MindHelp!.
        /// </summary>
        internal static string WelcomeBackMindHelp {
            get {
                return ResourceManager.GetString("WelcomeBackMindHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your message here….
        /// </summary>
        internal static string WriteMessagePlaceholder {
            get {
                return ResourceManager.GetString("WriteMessagePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your review here....
        /// </summary>
        internal static string WriteReviewHere {
            get {
                return ResourceManager.GetString("WriteReviewHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}y.
        /// </summary>
        internal static string YearsAgoFormat {
            get {
                return ResourceManager.GetString("YearsAgoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Years Exp..
        /// </summary>
        internal static string YearsExpFormat {
            get {
                return ResourceManager.GetString("YearsExpFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Years old.
        /// </summary>
        internal static string YearsOldFormat {
            get {
                return ResourceManager.GetString("YearsOldFormat", resourceCulture);
            }
        }
    }
}
